import { Separator } from "@/components/ui/separator";

const Footer = () => {
  return (
    <footer className="px-5 pt-8 pb-28 mt-6">
      <Separator className="mb-6 bg-border" />

      {/* Brand */}
      <p className="font-display text-lg text-gold tracking-wider text-center mb-4">
        LUXE
      </p>

      {/* About Us */}
      <div className="mb-5">
        <p className="font-body text-[10px] uppercase tracking-widest text-muted-foreground mb-2">
          About Us
        </p>
        <p className="font-body text-xs text-muted-foreground leading-relaxed">
          LuxGlow is an AI beauty stylist that recommends makeup based on skin tone, outfit and personal style.
          Users are matched with beauty products from major brands and redirected to official websites to purchase recommended items.
          We connect users to recommended products from top beauty brands through seamless in-app discovery.
        </p>
      </div>

      {/* Disclaimer */}
      <div className="mb-5">
        <p className="font-body text-[10px] uppercase tracking-widest text-muted-foreground mb-2">
          Disclaimer
        </p>
        <p className="font-body text-[11px] text-muted-foreground/70 leading-relaxed">
          LuxGlow is not affiliated with or endorsed by any beauty brand featured in our recommendations.
          All product suggestions are generated by AI and are for informational purposes only.
          We do not sell products directly — users are redirected to official brand websites for purchases.
          Results may vary based on individual skin type, tone, and preferences.
        </p>
      </div>

      {/* Copyright */}
      <p className="font-body text-[10px] text-muted-foreground/50 text-center mt-4">
        © {new Date().getFullYear()} LuxGlow. All rights reserved.
      </p>
    </footer>
  );
};

export default Footer;
